ful1e5/onedark.nvim

- CHANGELOG.md
- README.md
- lua/onedark/theme.lua
https://user-images.githubusercontent.com/24286590/127478467-35663470-6170-4173-8e68-fdfb6dda9dff.mp4
> `barbar.nvim` plugin support ( related to monsonjeremy/onedark.nvim#8 )

- CHANGELOG.md
- extras/kitty_onedark.conf
- lua/onedark/colors.lua
- lua/onedark/extra/kitty.lua
- lua/onedark/theme.lua
> feat: `cursor` color

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: TSProperty Color

- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: variable_builtin highlight

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: `jsonTSLabel` color

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: `lessInclude` color

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: `makeIdent` color

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: php syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: python syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: javascript syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: ruby syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/config.lua
- lua/onedark/theme.lua
> feat: scss syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: bash syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: typescript syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: sql syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: xml syntax highlighting improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> feat: yaml syntax highlighting improved

- CHANGELOG.md
- lua/onedark/theme.lua
> fix: inactive statusline background color

- CHANGELOG.md
- lua/onedark/theme.lua
> fix: diagnostic highlights

- README.md
Hello,
Thanks for the nice theme!
I have added minor typo fix on the configuration table.
> Fixed typo `darkSidebar` on configuration table.

- lua/lualine/themes/onedark-nvim.lua
Added lualine theme based on https://github.com/folke/tokyonight.nvim/blob/main/lua/lualine/themes/tokyonight.lua
> feat(themes): add lualine theme

- lua/lualine/themes/onedark-nvim.lua
Sorry for all the commits having the exactly same wording, I forgot that folder based plugins are there in packer.nvim
> feat(lualine): better colors

- CHANGELOG.md
- README.md
- lua/lualine/themes/onedark-nvim.lua
- lua/onedark/colors.lua
- lua/onedark/config.lua
- lua/onedark/extra/alacritty.lua
- lua/onedark/extra/kitty.lua
- lua/onedark/init.lua
- lua/onedark/theme.lua
- lua/onedark/util.lua
- added hot reloaded to `onedark-nvim` lualine theme
- `lualine_bold` option added
- luadoc: fix warning inside config module
> feat: `onedark-nvim` lualine theme improved

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
> fix: diff text with comment text

- CHANGELOG.md
- lua/onedark/theme.lua
> fix: #71 in normal mode

- CHANGELOG.md
- lua/onedark/colors.lua
- lua/onedark/theme.lua
- lua/onedark/util.lua
- alias warning
- changes-log updated
> enhance: vscode like `nvim-cmp` highlights

- CHANGELOG.md
- README.md
- lua/onedark/theme.lua
> enhance: `nvim-cmp` all lspkind supported

- CHANGELOG.md
- lua/onedark/theme.lua
> Link common `diff` highlights group

- CHANGELOG.md
- lua/onedark/theme.lua
> Fix dark foreground color for visited entries in telescope.nvim

- CHANGELOG.md
- README.md
- lua/onedark/theme.lua
- [hop.nvim](https://github.com/phaazon/hop.nvim) plugin support
- Update log inside `CHANGELOG.md`
- [README#plugin-support](https://github.com/projekt0n/github-nvim-theme#plugin-support) updated
> feat: plugin support hop.nvim

- CHANGELOG.md
- README.md
- lua/onedark/theme.lua
> feat: basic coc.nvim diagnostic highlights supported

- README.md
Other Change:
- Typo in README.md
> Statusline config added in README.md

- CHANGELOG.md
- README.md
- lua/onedark/config.lua
- lua/onedark/theme.lua
- lua/onedark/util.lua
- Removed unnecessary defer function & highlights
> Refactor override function to util.lua module
